namespace: default
imagePullPolicy: Always
awsEfsCsiDriverNamespace: kube-system
frontend:
  replicaCount: 1
  image:
    repository: gokulmsfag/frontend-todo
    tag: v9
    containerPort: 80
  resources:
    requests:
      memory: 20Mi
      cpu: "0.25"
    limits:
      memory: 400Mi
      cpu: ".5"

  service:
    type: LoadBalancer
    port: 8001
    targetPort: 80

backend:
  image:
    repository: gokulmsfag/node-todo
    tag: v5
    containerPort: 8000
  resources:
    requests:
      memory: 20Mi
      cpu: "0.25"
    limits:
      memory: 400Mi
      cpu: "1"

  service:
    type: LoadBalancer
    port: 8000
    targetPort: 8000

mongo:
  image: mongo
  tag: latest
  containerPort: 27017

  volumeMounts:
    mountPath: /data/db

  resources:
    requests:
      memory: 250Mi
      cpu: "0.25"
    limits:
      memory: 500Mi
      cpu: ".5"

  service:
    type: ClusterIP
    port: 27017
    targetPort: 27017

storageClass:
  provisioner: hostpath
  volumeBindingMode: Immediate
  reclaimPolicy: Delete
  parameters:
    type: gp2

pv:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-04a2eaaf81773c01c

pvc:
  accessModes:
    - ReadWriteMany
  requests:
    storage: 10Gi
