apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.service.name" . }}
spec:
  selector:
    {{ include "frontend.deployment.selectorLabel" . | nindent 4 }}
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
