apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo.service.name" . }}
spec:
  selector:
    {{ include "mongo.deployment.selectorLabel" . | nindent 4 }}
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}
