apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mongo.pv.name" .}}
spec:
  capacity:
    {{toYaml .Values.pv.capacity | nindent 4}}
  volumeMode: {{ .Values.pv.volumeMode }}
  accessModes:
    {{ .Values.pv.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.persistentVolumeReclaimPolicy }}
  storageClassName: {{ include "storageclass.name" . }}
  csi:
    {{ toYaml .Values.pv.csi | nindent 4}}
