apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongo.deployment.name" . }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  selector:
    matchLabels:
      {{- include "mongo.deployment.selectorLabel" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mongo.deployment.selectorLabel" . | nindent 8 }}
    spec:
      containers:
        - name: {{ printf "%s-mongo" .Chart.Name }}
          image: {{ .Values.mongo.image }}:{{ .Values.mongo.tag }}
          ports:
            - containerPort: {{ .Values.mongo.containerPort }}
          volumeMounts:
            {{- include "mongo.deployment.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "mongo.deployment.volume" . | nindent 8 }}