apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "storageclass.name" . }}
provisioner: {{ .Values.storageClass.provisioner}}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy}}

# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: aws-ebs-sc
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2 # You can specify the EBS volume type, e.g., gp2, io1, etc.
